flowchart LR
    T[TRIGGER<br/>push / parent nudge /<br/>internal boredom] --> A[ACTION<br/>open app, hit big<br/>'Weiter üben' button]
    A --> R[VARIABLE REWARD<br/>points + occasional<br/>surprise unlock]
    R --> I[INVESTMENT<br/>avatar update,<br/>mastery bar grows,<br/>friend-ship updates]
    I -.next day.-> T
