/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    exercises: Exercise;
    'prompt-templates': PromptTemplate;
    'audit-log': AuditLog;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    exercises: ExercisesSelect<false> | ExercisesSelect<true>;
    'prompt-templates': PromptTemplatesSelect<false> | PromptTemplatesSelect<true>;
    'audit-log': AuditLogSelect<false> | AuditLogSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {};
  globalsSelect: {};
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  role: 'admin' | 'reviewer' | 'family';
  /**
   * Shown in the reviewer queue and audit log.
   */
  displayName?: string | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "exercises".
 */
export interface Exercise {
  id: number;
  title: string;
  /**
   * Shown once per session before the task. Dismissible after first view.
   */
  intro: {
    /**
     * What you will do.
     */
    what: string;
    /**
     * Why it matters.
     */
    why: string;
    workedExample?: {
      root: {
        type: string;
        children: {
          type: any;
          version: number;
          [k: string]: unknown;
        }[];
        direction: ('ltr' | 'rtl') | null;
        format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
        indent: number;
        version: number;
      };
      [k: string]: unknown;
    } | null;
  };
  format:
    | 'tap_to_tag'
    | 'multiple_choice'
    | 'multi_select'
    | 'fill_blank'
    | 'drag_drop'
    | 'sentence_building'
    | 'audio'
    | 'image'
    | 'error_spotting'
    | 'transformation'
    | 'writing';
  /**
   * 5–12 items keyed to the chosen format. Structure is format-specific — see src/validators/items/.
   */
  items:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  section: 'sprachbetrachtung' | 'aufsatz' | 'textverstaendnis' | 'rechtschreibung' | 'assessment';
  /**
   * e.g. Wortarten, Satzglieder, Kasus.
   */
  topic: string;
  /**
   * e.g. Nomen erkennen, Akkusativ vs Dativ.
   */
  subtopic?: string | null;
  difficulty: number;
  /**
   * 1 = tangential, 2 = common, 3 = high-frequency exam topic. Drives recommendation weighting.
   */
  examRelevance: number;
  cantonApplicability: ('ZH' | 'BE' | 'LU' | 'ALL')[];
  estimatedTimeSec: number;
  lifecycleState: 'generated' | 'published' | 'rejected' | 'retired';
  /**
   * Required when state = rejected.
   */
  rejectionReason?: string | null;
  /**
   * Where this exercise came from and who touched it.
   */
  provenance?: {
    /**
     * The template used to generate this item (null if authored manually).
     */
    promptTemplate?: (number | null) | PromptTemplate;
    /**
     * Shared across all items from a single AI run, for traceability.
     */
    generationBatchId?: string | null;
    /**
     * The reviewer who most recently approved/edited/rejected.
     */
    reviewer?: (number | null) | User;
    reviewedAt?: string | null;
  };
  /**
   * Real-world usage stats. Populated by the app; divergence from `difficulty` triggers re-review.
   */
  performance?: {
    attempts?: number | null;
    /**
     * 0.0–1.0
     */
    correctRate?: number | null;
    avgTimeSec?: number | null;
    lastComputedAt?: string | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "prompt-templates".
 */
export interface PromptTemplate {
  id: number;
  name: string;
  format:
    | 'tap_to_tag'
    | 'multiple_choice'
    | 'multi_select'
    | 'fill_blank'
    | 'drag_drop'
    | 'sentence_building'
    | 'audio'
    | 'image'
    | 'error_spotting'
    | 'transformation'
    | 'writing';
  topic: string;
  subtopic?: string | null;
  version: number;
  /**
   * Only one version per (format, topic, subtopic) should be active at a time. Enforced softly — the generation script picks isActive=true.
   */
  isActive?: boolean | null;
  /**
   * Role and style guardrails. Should reference the five learning principles.
   */
  systemPrompt: string;
  /**
   * Instructions for the model. Use {{placeholders}} for per-batch variables (e.g. {{difficulty}}, {{count}}).
   */
  userPromptTemplate: string;
  /**
   * JSON schema the generator output must conform to. Used by auto-validation.
   */
  outputJsonSchema:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * Admin-only notes on what this template is for, known failure modes, etc.
   */
  notes?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "audit-log".
 */
export interface AuditLog {
  id: number;
  /**
   * One-line recap, e.g. "reviewer alice rejected exercise #412".
   */
  summary?: string | null;
  action: 'created' | 'transitioned' | 'edited';
  fromState?: string | null;
  toState?: string | null;
  exercise?: (number | null) | Exercise;
  actor?: (number | null) | User;
  reason?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'exercises';
        value: number | Exercise;
      } | null)
    | ({
        relationTo: 'prompt-templates';
        value: number | PromptTemplate;
      } | null)
    | ({
        relationTo: 'audit-log';
        value: number | AuditLog;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  role?: T;
  displayName?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "exercises_select".
 */
export interface ExercisesSelect<T extends boolean = true> {
  title?: T;
  intro?:
    | T
    | {
        what?: T;
        why?: T;
        workedExample?: T;
      };
  format?: T;
  items?: T;
  section?: T;
  topic?: T;
  subtopic?: T;
  difficulty?: T;
  examRelevance?: T;
  cantonApplicability?: T;
  estimatedTimeSec?: T;
  lifecycleState?: T;
  rejectionReason?: T;
  provenance?:
    | T
    | {
        promptTemplate?: T;
        generationBatchId?: T;
        reviewer?: T;
        reviewedAt?: T;
      };
  performance?:
    | T
    | {
        attempts?: T;
        correctRate?: T;
        avgTimeSec?: T;
        lastComputedAt?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "prompt-templates_select".
 */
export interface PromptTemplatesSelect<T extends boolean = true> {
  name?: T;
  format?: T;
  topic?: T;
  subtopic?: T;
  version?: T;
  isActive?: T;
  systemPrompt?: T;
  userPromptTemplate?: T;
  outputJsonSchema?: T;
  notes?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "audit-log_select".
 */
export interface AuditLogSelect<T extends boolean = true> {
  summary?: T;
  action?: T;
  fromState?: T;
  toState?: T;
  exercise?: T;
  actor?: T;
  reason?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}