/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    domains: Domain;
    modules: Module;
    units: Unit;
    concepts: Concept;
    'concept-prerequisites': ConceptPrerequisite;
    'exercise-groups': ExerciseGroup;
    'exercise-templates': ExerciseTemplate;
    'theory-blocks': TheoryBlock;
    'slot-pools': SlotPool;
    'slot-items': SlotItem;
    'l1-variants': L1Variant;
    'concept-cards': ConceptCard;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    domains: DomainsSelect<false> | DomainsSelect<true>;
    modules: ModulesSelect<false> | ModulesSelect<true>;
    units: UnitsSelect<false> | UnitsSelect<true>;
    concepts: ConceptsSelect<false> | ConceptsSelect<true>;
    'concept-prerequisites': ConceptPrerequisitesSelect<false> | ConceptPrerequisitesSelect<true>;
    'exercise-groups': ExerciseGroupsSelect<false> | ExerciseGroupsSelect<true>;
    'exercise-templates': ExerciseTemplatesSelect<false> | ExerciseTemplatesSelect<true>;
    'theory-blocks': TheoryBlocksSelect<false> | TheoryBlocksSelect<true>;
    'slot-pools': SlotPoolsSelect<false> | SlotPoolsSelect<true>;
    'slot-items': SlotItemsSelect<false> | SlotItemsSelect<true>;
    'l1-variants': L1VariantsSelect<false> | L1VariantsSelect<true>;
    'concept-cards': ConceptCardsSelect<false> | ConceptCardsSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {};
  globalsSelect: {};
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  role: 'admin' | 'reviewer' | 'family';
  /**
   * Shown in the reviewer queue and audit log.
   */
  displayName?: string | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "domains".
 */
export interface Domain {
  id: number;
  name: string;
  /**
   * Auto-generated from name if left blank.
   */
  slug: string;
  examStrand: 'assessed' | 'supporting';
  /**
   * Lower numbers appear first in the tree.
   */
  displayOrder: number;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "modules".
 */
export interface Module {
  id: number;
  name: string;
  slug: string;
  domain: number | Domain;
  description?: string | null;
  displayOrder: number;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "units".
 */
export interface Unit {
  id: number;
  name: string;
  slug: string;
  module: number | Module;
  description?: string | null;
  displayOrder: number;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "concepts".
 */
export interface Concept {
  id: number;
  name: string;
  slug: string;
  unit: number | Unit;
  /**
   * One-sentence learner-facing description.
   */
  description?: string | null;
  /**
   * Flag if this concept targets a known DaZ confusion. Leave blank for neutral concepts.
   */
  dazPainPoint?: ('gender' | 'cases' | 'tenses' | 'word_order' | 'separable_verbs') | null;
  /**
   * 1 = trivial, 5 = very hard. Calibrated later from telemetry.
   */
  baseDifficulty: number;
  /**
   * Expected total attempts across intro + practice + review + checkpoint phases.
   */
  targetAttempts: number;
  displayOrder: number;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "concept-prerequisites".
 */
export interface ConceptPrerequisite {
  id: number;
  /**
   * The concept that has the prerequisite.
   */
  concept: number | Concept;
  /**
   * The concept that must be known first.
   */
  prerequisite: number | Concept;
  strength: 'hard' | 'soft';
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "exercise-groups".
 */
export interface ExerciseGroup {
  id: number;
  name: string;
  /**
   * Globally unique.
   */
  slug: string;
  /**
   * Optional. Groups are phase-bundle attributes, not structural. Templates carry their own curriculum anchor.
   */
  concept?: (number | null) | Concept;
  phase: 'intro' | 'practice' | 'review' | 'checkpoint';
  /**
   * Number of correct items needed to complete this phase for a learner.
   */
  targetItems: number;
  displayOrder: number;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "exercise-templates".
 */
export interface ExerciseTemplate {
  id: number;
  /**
   * Primary curriculum anchor. Anchor at the narrowest level that fits (concept for single-concept exercises; unit/section/module/domain for cross-concept exercises).
   */
  primaryAnchor:
    | {
        relationTo: 'domains';
        value: number | Domain;
      }
    | {
        relationTo: 'modules';
        value: number | Module;
      }
    | {
        relationTo: 'units';
        value: number | Unit;
      }
    | {
        relationTo: 'concepts';
        value: number | Concept;
      };
  /**
   * Optional cross-references (max 2). Use when an exercise genuinely spans multiple concepts, units, or domains.
   */
  secondaryAnchors?:
    | {
        anchor:
          | {
              relationTo: 'domains';
              value: number | Domain;
            }
          | {
              relationTo: 'modules';
              value: number | Module;
            }
          | {
              relationTo: 'units';
              value: number | Unit;
            }
          | {
              relationTo: 'concepts';
              value: number | Concept;
            };
        id?: string | null;
      }[]
    | null;
  /**
   * Optional phase-bundle attribute (intro / practice / review / checkpoint). Not structural — curriculum position comes from primaryAnchor.
   */
  exerciseGroup?: (number | null) | ExerciseGroup;
  format:
    | 'single_choice'
    | 'multi_select'
    | 'fill_blank'
    | 'tap_text'
    | 'drag_order'
    | 'drag_sort'
    | 'matching_pairs'
    | 'voice_answer'
    | 'free_text_short'
    | 'dictation'
    | 'passage_comprehension'
    | 'essay_writing'
    | 'game_wordhunt'
    | 'game_speedcat'
    | 'conversational_exchange';
  cognitiveType: 'recognition' | 'classification' | 'generation' | 'transformation' | 'application';
  difficulty: number;
  /**
   * The learner-facing prompt. Use `{SLOT_NAME}` to reference slot items, e.g. "Welches Genus hat {NOUN}?".
   */
  promptPattern: string;
  /**
   * How to derive and evaluate the correct answer. Shape depends on format — see docs/collections/exercise-templates.md (to be written).
   */
  answerSpec:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * Array of {slot_name, pool_slug, tier_min, tier_max}. Leave empty for AI-native templates.
   */
  slotDefinitions?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  generationMode: 'static' | 'hybrid' | 'ai_native';
  /**
   * Prompt sent to the model for hybrid / ai_native modes. Ignored when generationMode = static.
   */
  aiPrompt?: string | null;
  /**
   * Progressive hints shown on repeated wrong answers. First is gentlest, last gives the answer.
   */
  hintLadder?:
    | {
        text: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Shown on correct answer. Slot placeholders allowed.
   */
  feedbackCorrect?: string | null;
  /**
   * Multi-select / partial credit.
   */
  feedbackPartial?: string | null;
  /**
   * Shown on wrong answer before walkthrough.
   */
  feedbackWrong?: string | null;
  /**
   * Long-form explanation after exhausting hints.
   */
  feedbackWalkthrough?: string | null;
  tags?:
    | {
        value: string;
        id?: string | null;
      }[]
    | null;
  status: 'draft' | 'in_review' | 'approved' | 'active' | 'flagged' | 'retired';
  version: number;
  /**
   * The older template this version replaces, if any.
   */
  supersedes?: (number | null) | ExerciseTemplate;
  /**
   * Set by hook on create.
   */
  createdBy?: (number | null) | User;
  approvedBy?: (number | null) | User;
  approvedAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "theory-blocks".
 */
export interface TheoryBlock {
  id: number;
  title: string;
  concept: number | Concept;
  format: 'conversational' | 'interactive_diagram' | 'mini_game' | 'video' | 'passage' | 'worked_example';
  l1: 'de' | 'en' | 'uk' | 'ru' | 'it' | 'pt';
  /**
   * Format-specific payload. See docs/collections/theory-blocks.md for shapes.
   */
  content:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  status: 'draft' | 'in_review' | 'approved' | 'active' | 'flagged' | 'retired';
  version: number;
  /**
   * The older block this version replaces.
   */
  supersedes?: (number | null) | TheoryBlock;
  createdBy?: (number | null) | User;
  approvedBy?: (number | null) | User;
  approvedAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "slot-pools".
 */
export interface SlotPool {
  id: number;
  name: string;
  slug: string;
  description?: string | null;
  /**
   * e.g. "noun", "verb", "adjective", "sentence", "passage". Free-form.
   */
  contentType: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "slot-items".
 */
export interface SlotItem {
  id: number;
  pool: number | SlotPool;
  /**
   * The concrete value substituted into templates.
   */
  value: string;
  /**
   * Arbitrary structured data, e.g. {genus, plural, frequency}. Accessed in templates via dot-paths: {NOUN.metadata.artikel}.
   */
  metadata?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  difficultyTier: number;
  /**
   * Uncheck to retire without deleting.
   */
  active: boolean;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "l1-variants".
 */
export interface L1Variant {
  id: number;
  parentType: 'theory_block' | 'exercise_template' | 'concept_card';
  /**
   * ID of the parent row in the collection named by parentType. UUID or numeric.
   */
  parentId: string;
  l1: 'de' | 'en' | 'uk' | 'ru' | 'it' | 'pt';
  /**
   * Content shape mirrors the parent type (bubbles for theory_block, prompt/answer for exercise_template, etc.).
   */
  content:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  status: 'draft' | 'in_review' | 'approved' | 'active' | 'flagged' | 'retired';
  approvedBy?: (number | null) | User;
  approvedAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "concept-cards".
 */
export interface ConceptCard {
  id: number;
  concept: number | Concept;
  l1: 'de' | 'en' | 'uk' | 'ru' | 'it' | 'pt';
  /**
   * One-paragraph definition in the target L1.
   */
  definition: string;
  /**
   * Concrete sentences that illustrate the concept.
   */
  examples?:
    | {
        text: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Known misconceptions bilingual learners bring to this concept.
   */
  commonConfusions?: string | null;
  /**
   * Related concepts the mascot may link to.
   */
  crossReferences?: (number | Concept)[] | null;
  status: 'draft' | 'in_review' | 'approved' | 'active' | 'flagged' | 'retired';
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'domains';
        value: number | Domain;
      } | null)
    | ({
        relationTo: 'modules';
        value: number | Module;
      } | null)
    | ({
        relationTo: 'units';
        value: number | Unit;
      } | null)
    | ({
        relationTo: 'concepts';
        value: number | Concept;
      } | null)
    | ({
        relationTo: 'concept-prerequisites';
        value: number | ConceptPrerequisite;
      } | null)
    | ({
        relationTo: 'exercise-groups';
        value: number | ExerciseGroup;
      } | null)
    | ({
        relationTo: 'exercise-templates';
        value: number | ExerciseTemplate;
      } | null)
    | ({
        relationTo: 'theory-blocks';
        value: number | TheoryBlock;
      } | null)
    | ({
        relationTo: 'slot-pools';
        value: number | SlotPool;
      } | null)
    | ({
        relationTo: 'slot-items';
        value: number | SlotItem;
      } | null)
    | ({
        relationTo: 'l1-variants';
        value: number | L1Variant;
      } | null)
    | ({
        relationTo: 'concept-cards';
        value: number | ConceptCard;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  role?: T;
  displayName?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "domains_select".
 */
export interface DomainsSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  examStrand?: T;
  displayOrder?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "modules_select".
 */
export interface ModulesSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  domain?: T;
  description?: T;
  displayOrder?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "units_select".
 */
export interface UnitsSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  module?: T;
  description?: T;
  displayOrder?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "concepts_select".
 */
export interface ConceptsSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  unit?: T;
  description?: T;
  dazPainPoint?: T;
  baseDifficulty?: T;
  targetAttempts?: T;
  displayOrder?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "concept-prerequisites_select".
 */
export interface ConceptPrerequisitesSelect<T extends boolean = true> {
  concept?: T;
  prerequisite?: T;
  strength?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "exercise-groups_select".
 */
export interface ExerciseGroupsSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  concept?: T;
  phase?: T;
  targetItems?: T;
  displayOrder?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "exercise-templates_select".
 */
export interface ExerciseTemplatesSelect<T extends boolean = true> {
  primaryAnchor?: T;
  secondaryAnchors?:
    | T
    | {
        anchor?: T;
        id?: T;
      };
  exerciseGroup?: T;
  format?: T;
  cognitiveType?: T;
  difficulty?: T;
  promptPattern?: T;
  answerSpec?: T;
  slotDefinitions?: T;
  generationMode?: T;
  aiPrompt?: T;
  hintLadder?:
    | T
    | {
        text?: T;
        id?: T;
      };
  feedbackCorrect?: T;
  feedbackPartial?: T;
  feedbackWrong?: T;
  feedbackWalkthrough?: T;
  tags?:
    | T
    | {
        value?: T;
        id?: T;
      };
  status?: T;
  version?: T;
  supersedes?: T;
  createdBy?: T;
  approvedBy?: T;
  approvedAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "theory-blocks_select".
 */
export interface TheoryBlocksSelect<T extends boolean = true> {
  title?: T;
  concept?: T;
  format?: T;
  l1?: T;
  content?: T;
  status?: T;
  version?: T;
  supersedes?: T;
  createdBy?: T;
  approvedBy?: T;
  approvedAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "slot-pools_select".
 */
export interface SlotPoolsSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  description?: T;
  contentType?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "slot-items_select".
 */
export interface SlotItemsSelect<T extends boolean = true> {
  pool?: T;
  value?: T;
  metadata?: T;
  difficultyTier?: T;
  active?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "l1-variants_select".
 */
export interface L1VariantsSelect<T extends boolean = true> {
  parentType?: T;
  parentId?: T;
  l1?: T;
  content?: T;
  status?: T;
  approvedBy?: T;
  approvedAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "concept-cards_select".
 */
export interface ConceptCardsSelect<T extends boolean = true> {
  concept?: T;
  l1?: T;
  definition?: T;
  examples?:
    | T
    | {
        text?: T;
        id?: T;
      };
  commonConfusions?: T;
  crossReferences?: T;
  status?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}